<!doctype html><html lang="es"><head><meta charset="UTF-8"><style>
@page{margin:14px}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#111;margin:0}.center{text-align:center}.right{text-align:right}.bold{font-weight:bold}.title{font-size:13px}.line{border-top:1px dashed #222;margin:6px 0}.break{word-break:break-all}table{width:100%;border-collapse:collapse}td,th{padding:2px}.totals td:first-child{text-align:right}.highlight{background:#eee;font-weight:bold}.cancelled{font-size:25px;color:#b71c1c;text-align:center;font-weight:bold;margin:8px}.qr{width:105px;height:105px}
</style></head><body>
<div class="center"><div class="title bold">FACTURA</div><div class="bold">CON DERECHO A CRÉDITO FISCAL</div><div class="title">{{ $company->nombre_empresa }}</div><div>Casa Matriz - Punto de Venta {{ config('siat.punto_venta') }}</div><div>{{ $company->direccion }}</div><div>Tel. {{ $company->telefono }} - {{ config('siat.municipio') }}</div></div>
<div class="line"></div><div class="center"><b>NIT</b><br>{{ $company->nit }}<br><b>FACTURA N°</b><br>{{ $sale->id }}<br><b>CÓD. AUTORIZACIÓN</b><br><span class="break">{{ $sale->cuf }}</span></div>
<div class="line"></div><table><tr><td class="right bold">NOMBRE/RAZÓN SOCIAL:</td><td>{{ $sale->cliente_nombre ?: 'SIN NOMBRE' }}</td></tr><tr><td class="right bold">NIT/CI/CEX:</td><td>{{ $sale->numero_documento }}{{ $sale->complemento ? '-'.$sale->complemento : '' }}</td></tr><tr><td class="right bold">FECHA DE EMISIÓN:</td><td>{{ optional($sale->fecha_emision_siat ?: $sale->fecha)->format('d/m/Y H:i:s') }}</td></tr><tr><td class="right bold">USUARIO:</td><td>{{ $sale->usuario?->username ?: $sale->usuario_nombre }}</td></tr></table>
<div class="line"></div><div class="center bold">DETALLE</div><table>@foreach($sale->detalles as $item)<tr><td colspan="2" class="bold">{{ $item->codigo_barras ?: $item->codigo }} - {{ $item->nombre }}</td></tr><tr><td>{{ number_format((float)$item->cantidad, 2) }} X {{ number_format((float)$item->precio_venta, 2) }} - {{ number_format((float)$item->descuento, 2) }}</td><td class="right">{{ number_format((float)$item->subtotal, 2) }}</td></tr>@endforeach</table>
<table class="totals"><tr><td>SUBTOTAL Bs</td><td class="right">{{ number_format((float)$sale->subtotal, 2) }}</td></tr><tr><td>(-) DESCUENTO Bs</td><td class="right">{{ number_format((float)$sale->descuento, 2) }}</td></tr><tr class="highlight"><td>MONTO TOTAL A PAGAR Bs</td><td class="right">{{ number_format((float)$sale->total, 2) }}</td></tr><tr class="highlight"><td>IMPORTE BASE CRÉDITO FISCAL</td><td class="right">{{ number_format((float)$sale->total, 2) }}</td></tr></table>
<div class="line"></div><div class="center">ESTA FACTURA CONTRIBUYE AL DESARROLLO DEL PAÍS, EL USO ILÍCITO SERÁ SANCIONADO PENALMENTE DE ACUERDO A LEY</div><p class="center">{{ config('siat.leyenda') }}</p>@if($sale->estado_siat==='PENDIENTE_EVENTO')<p class="center bold">“Este documento es la Representación Gráfica de un Documento Fiscal Digital emitido fuera de línea. Verifique posteriormente su envío con su proveedor o en www.impuestos.gob.bo”</p><div class="center bold" style="color:#e65100;font-size:11px">EMITIDA FUERA DE LÍNEA</div>@else<p class="center bold">“Este documento es la Representación Gráfica de un Documento Fiscal Digital emitido en una modalidad de facturación en línea”</p>@endif<div class="center"><img class="qr" src="{{ $qrDataUri }}"></div>
@if($sale->estado==='ANULADA'||$sale->estado_siat==='ANULADA')<div class="cancelled">ANULADA</div>@endif
</body></html>
