<template>
  <q-page class="q-pa-sm">
    <q-dialog v-model="purchaseDialog" persistent :maximized="$q.screen.lt.sm">
      <q-card class="column no-wrap" style="width:620px;max-width:94vw;max-height:92vh">
        <q-card-section class="row items-center q-pa-sm bg-primary text-white"><q-icon name="add_business" size="26px"/><div class="q-ml-sm"><div class="text-subtitle1 text-weight-bold">Confirmar compra</div><div class="text-caption">Proveedor y datos de compra</div></div><q-space/><q-btn flat round dense icon="close" color="white" v-close-popup/></q-card-section>
        <q-card-section class="col scroll q-pa-sm">
          <div class="row q-col-gutter-xs"><q-select v-model="provider" :options="providers" option-label="nombre" dense outlined label="Proveedor *" class="col"/><q-btn dense flat round color="primary" icon="person_add" @click="providerDialog=true"/></div>
          <q-card v-if="provider" flat bordered class="q-pa-sm q-mt-xs bg-red-1"><div class="text-weight-bold">{{provider.nombre}}</div><div class="text-caption">NIT: {{provider.nit||'Sin NIT'}} · Tel: {{provider.telefono||'Sin teléfono'}}</div><div v-if="provider.direccion" class="text-caption">{{provider.direccion}}</div></q-card>
          <div class="row q-col-gutter-sm q-mt-xs"><q-input v-model="invoice" dense outlined label="Número de factura" class="col-12 col-sm-6"/><q-select v-model="paymentType" :options="paymentTypes" dense outlined label="Tipo de pago *" class="col-12 col-sm-6"/></div>
          <div v-if="paymentType==='COMBINADO'" class="row q-col-gutter-sm q-mt-xs"><q-input v-model.number="cashAmount" dense outlined type="number" min="0" step="0.01" label="Monto efectivo" prefix="Bs" class="col-6"/><q-input v-model.number="qrAmount" dense outlined type="number" min="0" step="0.01" label="Monto QR" prefix="Bs" class="col-6"/><div class="col-12 text-caption" :class="paymentDifference===0?'text-positive':'text-negative'">Diferencia: Bs {{money(paymentDifference)}}</div></div>
          <q-banner v-else dense rounded :class="paymentType==='EFECTIVO'?'bg-green-1 text-green-9':'bg-blue-1 text-blue-9'" class="q-mt-xs"><q-icon :name="paymentType==='EFECTIVO'?'payments':'qr_code_2'" class="q-mr-xs"/>Pago {{paymentType}}: Bs {{money(total)}}</q-banner>
          <q-input v-model="comment" dense outlined autogrow label="Comentario" class="q-mt-sm"/>
          <div class="row items-center q-mt-sm q-pa-sm rounded-borders bg-blue-grey-9 text-white"><div><div class="text-caption">TOTAL DE COMPRA</div><div class="text-h5 text-weight-bold">Bs {{money(total)}}</div></div><q-space/><div class="text-caption">{{items.length}} productos</div></div>
        </q-card-section>
        <q-separator/><q-card-actions align="right" class="q-pa-sm"><q-btn flat dense label="Volver" no-caps v-close-popup/><q-btn color="positive" dense unelevated icon="save" label="Guardar compra" no-caps :loading="saving" @click="save"/></q-card-actions>
      </q-card>
    </q-dialog>
<!--    <CompanyBanner class="q-mb-sm"/>-->
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Nueva compra</div><div class="text-caption text-grey-7">Agrega mercadería al inventario</div></div><q-space/><q-btn flat dense icon="groups" label="Proveedores" no-caps to="/proveedores"/><q-btn flat dense icon="shopping_bag" label="Ver compras" no-caps to="/compras"/></div>
    <div class="row q-col-gutter-sm">
      <div class="col-12 col-lg-6">
        <q-card flat bordered>
          <q-card-section class="row q-col-gutter-sm q-pa-sm"><q-input ref="searchInput" v-model="search" dense outlined autofocus clearable debounce="250" class="col" placeholder="Buscar o escanear producto" @update:model-value="resetProductsPage" @keydown.enter.prevent="addExact"><template #prepend><q-icon name="qr_code_scanner"/></template></q-input><div class="col-auto flex items-center"><q-btn dense unelevated color="primary" icon="sync" label="Actualizar precio" no-caps :loading="refreshingPrices" @click="refreshPrices"/></div></q-card-section>
          <q-separator/><q-card-section v-if="loadingProducts" class="flex flex-center product-loading"><q-spinner color="primary" size="36px"/></q-card-section><q-card-section v-else class="q-pa-sm product-grid"><q-card v-for="product in products" :key="product.id" flat bordered class="product-card cursor-pointer" @click="add(product)"><div class="product-image"><img v-if="product.foto" :src="photoUrl(product.foto)"/><q-icon v-else name="inventory_2" size="34px" color="grey-4"/></div><q-card-section class="q-pa-xs"><div class="text-caption text-weight-bold ellipsis-2-lines product-name">{{product.nombre}}</div><div class="text-caption text-grey-7 ellipsis">{{product.codigo}} · {{product.unidad}}</div><div class="row items-center no-wrap product-meta"><b class="text-primary">Bs {{money(product.precio_compra)}}</b><q-space/><span>Stock {{qty(product.stock_inicial,product.unidad)}}</span></div></q-card-section></q-card></q-card-section>
          <q-separator/><q-card-actions class="row items-center justify-between q-px-sm"><span class="text-caption text-grey-7">{{productsFrom}}–{{productsTo}} de {{productsTotal}} productos</span><q-pagination v-model="productsPage" :max="productsLastPage" :max-pages="5" boundary-numbers direction-links color="primary" size="sm" @update:model-value="loadProducts"/></q-card-actions>
        </q-card>
      </div>
      <div class="col-12 col-lg-6">
        <q-card flat bordered class="purchase-card"><q-card-section class="row items-center q-py-sm"><q-icon name="shopping_cart" color="primary" size="22px" class="q-mr-xs"/><b>Productos</b><q-space/><q-badge color="primary" :label="items.length"/></q-card-section><q-separator/>
          <q-list v-if="items.length" separator class="item-list"><q-item v-for="item in items" :key="item.line_id" dense class="q-px-xs purchase-item"><q-item-section avatar class="item-thumb"><q-avatar rounded size="28px" color="grey-2"><img v-if="item.foto" :src="photoUrl(item.foto)"/><q-icon v-else name="inventory_2" size="18px"/></q-avatar></q-item-section><q-item-section class="item-content"><q-item-label lines="1" class="text-caption text-weight-medium item-name">{{item.nombre}}</q-item-label><div class="item-fields-row no-wrap"><label class="compact-label"><span>Cant.</span><input v-model.number="item.cantidad" class="qty-input" type="number" min="0.001" step="0.001" @input="syncItemTotal(item)"></label><label class="compact-label"><span>Costo</span><input v-model.number="item.precio_unitario" class="price-input" type="number" min="0" step="0.0001" @input="syncItemTotal(item)"></label><label class="compact-label total-label"><span>Total</span><input v-model.number="item.total_editable" class="total-input" type="number" min="0" step="0.01" @blur="applyItemTotal(item)"></label><label class="compact-label"><span>Lote</span><input v-model="item.lote" class="extra-input" placeholder="Opcional"></label><label class="compact-label"><span>Vencimiento</span><input v-model="item.fecha_vencimiento" class="extra-input date-input" type="date"></label><q-btn dense flat round size="xs" icon="delete" color="negative" @click="remove(item)"/></div></q-item-section></q-item></q-list>
          <q-card-section v-else class="text-center text-grey-6 q-py-lg">Agrega productos</q-card-section><q-separator/><q-card-section class="row text-h6 text-primary q-py-sm"><b>Total</b><q-space/><b>Bs {{money(total)}}</b></q-card-section><q-card-actions class="q-pa-sm"><q-btn class="full-width" color="positive" unelevated icon="arrow_forward" label="Continuar" no-caps :disable="!items.length" @click="openPurchaseDialog"/></q-card-actions>
        </q-card>
      </div>
    </div>
    <q-dialog v-model="providerDialog"><q-card style="width:460px;max-width:94vw"><q-form @submit="saveProvider"><q-card-section class="row"><b>Nuevo proveedor</b><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-card-section class="q-gutter-sm"><q-input v-model="providerForm.nombre" dense outlined label="Nombre *"/><q-input v-model="providerForm.nit" dense outlined label="NIT"/><q-input v-model="providerForm.telefono" dense outlined label="Teléfono"/><q-input v-model="providerForm.direccion" dense outlined label="Dirección"/></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" label="Guardar" type="submit" :loading="providerSaving"/></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, onMounted, reactive, ref, watch } from 'vue'
import { printPurchase } from '../../addons/compraPrint'
import CompanyBanner from '../../components/CompanyBanner.vue'
import { useCartsStore } from '../../stores/carts'
const {proxy}=getCurrentInstance(),cartsStore=useCartsStore()
// Los datos de la compra en curso viven en el store (persistido en localStorage).
const compraField=name=>computed({get:()=>cartsStore.compra[name],set:value=>{cartsStore.compra[name]=value}})
const items=compraField('items'),provider=compraField('proveedor'),invoice=compraField('numero_factura'),comment=compraField('comentario'),paymentType=compraField('tipo_pago'),cashAmount=compraField('monto_efectivo'),qrAmount=compraField('monto_qr')
const products=ref([]),providers=ref([]),search=ref(''),saving=ref(false),providerSaving=ref(false),refreshingPrices=ref(false),searchInput=ref(null),providerDialog=ref(false),purchaseDialog=ref(false)
const productsPage=ref(1),productsLastPage=ref(1),productsTotal=ref(0),productsFrom=ref(0),productsTo=ref(0),loadingProducts=ref(false)
const productsPerPage=15
const paymentTypes=['EFECTIVO','QR','COMBINADO'],providerForm=reactive({nombre:'',nit:'',telefono:'',direccion:''})
const photoUrl=path=>`${proxy.$imgBase}/images/${path}`,money=v=>Number(v||0).toFixed(2),qty=(v,u)=>Number(v||0).toFixed(u==='KG'?3:0),lineTotal=i=>Number(i.cantidad||0)*Number(i.precio_unitario||0),total=computed(()=>items.value.reduce((s,i)=>s+Number(i.total_editable||0),0))
const paymentDifference=computed(()=>Number((total.value-(Number(cashAmount.value)||0)-(Number(qrAmount.value)||0)).toFixed(2)))
watch([paymentType,total],()=>{if(paymentType.value==='EFECTIVO'){cashAmount.value=total.value;qrAmount.value=0}else if(paymentType.value==='QR'){cashAmount.value=0;qrAmount.value=total.value}else if(Number(cashAmount.value)+Number(qrAmount.value)===0){cashAmount.value=total.value;qrAmount.value=0}})
const daysUntil=value=>Math.ceil((new Date(`${value}T12:00:00`)-new Date())/86400000),expiryLabel=value=>daysUntil(value)<0?`Vencido hace ${Math.abs(daysUntil(value))} días`:`Vence en ${daysUntil(value)} días`
async function loadProducts(){loadingProducts.value=true;try{const{data}=await proxy.$axios.get('/productos',{params:{q:search.value,per_page:productsPerPage,page:productsPage.value}});products.value=data.data;productsLastPage.value=data.last_page||1;productsTotal.value=data.total||0;productsFrom.value=data.from||0;productsTo.value=data.to||0;if(productsPage.value>productsLastPage.value){productsPage.value=productsLastPage.value;await loadProducts()}}finally{loadingProducts.value=false}}
function resetProductsPage(){productsPage.value=1;loadProducts()}
async function refreshPrices(){if(refreshingPrices.value)return;refreshingPrices.value=true;try{await loadProducts();const currentById=new Map((await proxy.$axios.get('/productos',{params:{per_page:0}})).data.data.map(product=>[product.id,product]));items.value.forEach(item=>{const current=currentById.get(item.id);if(!current)return;item.precio_unitario=Number(current.precio_compra||0);syncItemTotal(item)});proxy.$alert.success(items.value.length?'Precios del catálogo y productos actualizados':'Precios actualizados')}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudieron actualizar los precios')}finally{refreshingPrices.value=false;searchInput.value?.focus()}}
function loadProviders(){proxy.$axios.get('/proveedores').then(r=>providers.value=r.data)}
function add(p){const item={...p,line_id:`${p.id}-${Date.now()}-${Math.random()}`,cantidad:1,precio_unitario:Number(p.precio_compra),total_editable:Number(p.precio_compra).toFixed(2),lote:'',fecha_vencimiento:''};items.value.push(item);return item}
async function addExact(){const q=String(search.value||'').trim();if(!q)return;const scale=/^2\d{12}$/.test(q)?{code:q.slice(0,7),weight:Number(q.slice(7,12))/1000}:null;const lookup=scale?.code||q;const{data}=await proxy.$axios.get('/productos',{params:{q:lookup,per_page:20,page:1}});const p=data.data.find(i=>i.codigo===lookup||i.codigo_barras===lookup);if(!p)return proxy.$alert.error(`No existe un producto con código ${lookup}`);const item=add(p);if(scale&&p.unidad==='KG'){item.cantidad=scale.weight;syncItemTotal(item)}search.value='';productsPage.value=1;loadProducts()}
function remove(i){items.value=items.value.filter(x=>x.line_id!==i.line_id)}
function syncItemTotal(item){item.total_editable=(Number(item.cantidad||0)*Number(item.precio_unitario||0)).toFixed(2)}
function applyItemTotal(item){const quantity=Number(item.cantidad||0),value=Math.max(0,Number(item.total_editable)||0);item.total_editable=value.toFixed(2);if(quantity>0)item.precio_unitario=Number((value/quantity).toFixed(4))}
function openPurchaseDialog(){if(items.value.some(i=>Number(i.cantidad)<=0))return proxy.$alert.error('Revise las cantidades');purchaseDialog.value=true}
function saveProvider(){if(!providerForm.nombre)return proxy.$alert.error('Ingrese el nombre');providerSaving.value=true;proxy.$axios.post('/proveedores',providerForm).then(r=>{providers.value.push(r.data);provider.value=r.data;providerDialog.value=false;Object.assign(providerForm,{nombre:'',nit:'',telefono:'',direccion:''});proxy.$alert.success('Proveedor guardado')}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo guardar el proveedor')).finally(()=>providerSaving.value=false)}
function save(){if(!provider.value)return proxy.$alert.error('Seleccione un proveedor');if(items.value.some(i=>Number(i.cantidad)<=0))return proxy.$alert.error('Revise las cantidades');if(paymentType.value==='COMBINADO'&&paymentDifference.value!==0)return proxy.$alert.error('Efectivo y QR deben sumar el total');saving.value=true;proxy.$axios.post('/compras',{proveedor_id:provider.value.id,numero_factura:invoice.value,tipo_pago:paymentType.value,monto_efectivo:cashAmount.value,monto_qr:qrAmount.value,comentario:comment.value,detalles:items.value.map(i=>({producto_id:i.id,cantidad:i.cantidad,precio_unitario:i.precio_unitario,lote:i.lote||null,fecha_vencimiento:i.fecha_vencimiento||null}))}).then(r=>{purchaseDialog.value=false;proxy.$alert.success(`Compra ${r.data.numero} registrada`);printPurchase(r.data);cartsStore.limpiarCompra();loadProducts();searchInput.value?.focus()}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo guardar')).finally(()=>saving.value=false)}
onMounted(()=>{loadProducts();loadProviders()})
</script>
<style scoped>
.product-loading{min-height:300px}.product-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(105px,1fr));gap:5px;max-height:calc(100vh - 200px);overflow:auto}.product-card{overflow:hidden}.product-card:hover{border-color:#f57c00;background:#fffaf5}.product-image{height:48px;background:#fffaf3;display:flex;align-items:center;justify-content:center}.product-image img{width:100%;height:100%;object-fit:contain}.product-name{height:32px;line-height:16px}.product-meta{font-size:11px}.purchase-card{position:sticky;top:62px}.item-list{max-height:68vh;overflow:auto}.purchase-item{min-height:54px;padding-top:3px;padding-bottom:3px}.item-thumb{min-width:34px;padding-right:6px}.item-content{min-width:0}.item-name{line-height:14px;margin-bottom:2px}.item-fields-row{display:flex;align-items:flex-end;gap:3px;white-space:nowrap;overflow-x:auto;padding-bottom:1px}.compact-label{font-size:9px;line-height:10px;color:#607d8b;display:flex;flex-direction:column;gap:1px}.qty-input,.price-input,.total-input,.extra-input{height:21px;border:1px solid #cfd8dc;border-radius:4px;padding:1px 3px;font-size:11px;color:#263238;background:#fff}.qty-input{width:42px}.price-input{width:52px}.total-input{width:56px;font-weight:700;color:#f57c00}.extra-input{width:62px}.date-input{width:102px}.qty-input:focus,.price-input:focus,.total-input:focus,.extra-input:focus{outline:1px solid #f57c00;border-color:#f57c00}@media(max-width:1023px){.purchase-card{position:static}.product-grid{max-height:none}.item-list{max-height:none}}@media(max-width:420px){.item-thumb{display:none}}
</style>
