<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Ventas</div><div class="text-caption text-grey-7">Resumen e historial de ventas</div></div><q-space/>
      <q-btn-dropdown dense flat color="primary" icon="download" label="Exportar" no-caps class="q-mr-xs" :loading="!!exporting" :disable="!!exporting"><q-list dense style="min-width:260px"><q-item clickable v-close-popup @click="download('excel')"><q-item-section avatar><q-icon name="table_view" color="positive"/></q-item-section><q-item-section><q-item-label>Excel de ventas</q-item-label><q-item-label caption>Ventas, productos y resumen</q-item-label></q-item-section></q-item><q-item clickable v-close-popup @click="download('pdf')"><q-item-section avatar><q-icon name="picture_as_pdf" color="negative"/></q-item-section><q-item-section><q-item-label>PDF de ventas</q-item-label><q-item-label caption>Listado para imprimir</q-item-label></q-item-section></q-item><q-separator/><q-item clickable v-close-popup @click="downloadChangedPrices('excel')"><q-item-section avatar><q-icon name="price_change" color="orange"/></q-item-section><q-item-section><q-item-label>Excel de precios modificados</q-item-label><q-item-label caption>Sólo productos con precio cambiado</q-item-label></q-item-section></q-item><q-item clickable v-close-popup @click="downloadChangedPrices('pdf')"><q-item-section avatar><q-icon name="picture_as_pdf" color="deep-orange"/></q-item-section><q-item-section><q-item-label>PDF de precios modificados</q-item-label><q-item-label caption>Sólo productos con precio cambiado</q-item-label></q-item-section></q-item></q-list></q-btn-dropdown>
      <q-btn v-if="can('Crear Ventas')" dense unelevated color="positive" icon="add_shopping_cart" label="Nueva venta" no-caps to="/ventas/nueva"/>
    </div>

    <div class="row q-col-gutter-sm q-mb-sm">
      <div v-for="card in cards" :key="card.label" class="col-6 col-md-2"><q-card flat bordered :class="`summary-card bg-${card.color}-1 text-${card.color}-9`"><q-card-section class="row items-center q-pa-sm"><q-avatar :color="card.color" text-color="white" :icon="card.icon" size="36px"/><div class="q-ml-sm"><div class="text-caption">{{card.label}}</div><div class="text-h6 text-weight-bold">{{card.money?'Bs ':''}}{{card.money?money(card.value):card.value}}</div></div></q-card-section></q-card></div>
    </div>

    <q-card flat bordered>
      <q-card-section class="row q-col-gutter-sm q-pa-sm">
        <q-input v-model="search" dense outlined debounce="300" clearable placeholder="Buscar número, usuario o estado" class="col-12 col-md-5" @update:model-value="() => load(true)"><template #prepend><q-icon name="search"/></template></q-input>
        <q-select v-model="user" :options="summary.usuarios" option-label="name" dense outlined clearable label="Usuario" class="col-12 col-md-2" @update:model-value="() => load(true)"/>
        <q-select v-model="receiptType" :options="[{label:'Facturadas',value:'FACTURA'},{label:'Otras',value:'RECIBO'}]" emit-value map-options dense outlined clearable label="Facturación" class="col-6 col-md-1" @update:model-value="() => load(true)"/>
        <q-select v-model="siatState" :options="siatStates" emit-value map-options dense outlined clearable label="Estado Impuestos" class="col-6 col-md-1" @update:model-value="() => load(true)"/>
        <q-btn dense flat no-caps color="primary" icon="today" label="Hoy" class="col-auto" @click="resetToday"><q-tooltip>Volver al día de hoy, jornada completa</q-tooltip></q-btn>
      </q-card-section>
      <q-card-section class="row q-col-gutter-sm q-pa-sm q-pt-none">
        <q-input v-model="from" dense outlined type="date" label="Desde" class="col-6 col-md-3" @update:model-value="() => load(true)"/>
        <q-input v-model="to" dense outlined type="date" label="Hasta" class="col-6 col-md-3" @update:model-value="() => load(true)"/>
        <q-input v-model="fromTime" dense outlined type="time" label="Desde hora" class="col-6 col-md-3" @update:model-value="() => load(true)"><template #prepend><q-icon name="schedule"/></template></q-input>
        <q-input v-model="toTime" dense outlined type="time" label="Hasta hora" class="col-6 col-md-3" @update:model-value="() => load(true)"><template #prepend><q-icon name="schedule"/></template></q-input>
      </q-card-section>
      <q-table dense flat :rows="rows" :columns="columns" row-key="id" :loading="loading" v-model:pagination="pagination" :rows-per-page-options="[15,30,50,100,0]" @request="onRequest">
        <template #body-cell-total="p"><q-td :props="p"><b>Bs {{money(p.value)}}</b></q-td></template>
        <template #body-cell-tipo_pago="p"><q-td :props="p"><q-chip dense square :color="paymentColor(p.value)" text-color="white" :icon="p.value==='QR'?'qr_code_2':p.value==='EFECTIVO'?'payments':'account_balance_wallet'">{{p.value}}</q-chip></q-td></template>
        <template #body-cell-detalles="p"><q-td :props="p"><div class="items-list"><div v-for="d in (p.row.detalles||[])" :key="d.id" class="items-row"><b>{{qty(d.cantidad)}}{{d.unidad==='KG'?'kg':''}}</b> {{d.nombre}}</div><q-tooltip v-if="p.row.detalles?.length"><div v-for="d in p.row.detalles" :key="d.id">{{qty(d.cantidad)}}{{d.unidad==='KG'?'kg':''}} · {{d.nombre}}</div></q-tooltip></div></q-td></template>
        <template #body-cell-estado="p"><q-td :props="p"><q-badge :color="p.value==='COMPLETADA'?'positive':'negative'" :label="p.value"/></q-td></template>
        <template #body-cell-comprobante="p"><q-td :props="p"><div v-if="p.row.tipo_comprobante==='FACTURA'"><b>FACTURA N° {{p.row.numero_factura}}</b><div class="items-row">{{p.row.cliente_nombre}} · {{p.row.numero_documento}}</div></div><span v-else class="text-grey-5">—</span></q-td></template>
        <template #body-cell-estado_siat="p"><q-td :props="p"><q-badge v-if="p.value" :color="siatColor(p.value)" :label="siatLabel(p.value)"/><q-tooltip v-if="p.row.siat_mensaje" max-width="320px">{{p.row.siat_mensaje}}</q-tooltip></q-td></template>
        <template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:150px"><q-item clickable v-close-popup @click="showDetail(p.row)"><q-item-section avatar><q-icon name="visibility" color="primary"/></q-item-section><q-item-section>Ver detalle</q-item-section></q-item><q-item v-if="p.row.cuf" clickable v-close-popup @click="printRow(p.row,'factura')"><q-item-section avatar><q-icon name="receipt" color="teal"/></q-item-section><q-item-section>Imprimir factura</q-item-section></q-item><q-item clickable v-close-popup @click="printRow(p.row,'comprobante')"><q-item-section avatar><q-icon name="print" color="blue-grey"/></q-item-section><q-item-section>{{p.row.cuf?'Imprimir comprobante':'Imprimir'}}</q-item-section></q-item><q-item v-if="p.row.factura_url" clickable v-close-popup tag="a" :href="p.row.factura_url" target="_blank" rel="noopener"><q-item-section avatar><q-icon name="open_in_new" color="indigo"/></q-item-section><q-item-section>Ver factura en Impuestos</q-item-section></q-item><q-item v-if="p.row.cuf" clickable v-close-popup @click="downloadPdf(p.row)"><q-item-section avatar><q-icon name="picture_as_pdf" color="negative"/></q-item-section><q-item-section>Descargar PDF</q-item-section></q-item><q-item v-if="p.row.cuf" clickable v-close-popup @click="sendMail(p.row)"><q-item-section avatar><q-icon name="forward_to_inbox" color="primary"/></q-item-section><q-item-section><q-item-label>Enviar factura por correo</q-item-label><q-item-label v-if="p.row.email_enviado_en" caption>Enviada {{formatDate(p.row.email_enviado_en)}}</q-item-label></q-item-section></q-item><q-item v-if="p.row.cuf" clickable v-close-popup @click="verify(p.row)"><q-item-section avatar><q-icon name="fact_check" color="teal"/></q-item-section><q-item-section>Verificar en Impuestos</q-item-section></q-item><q-item v-if="can('Crear Ventas')&&p.row.estado==='COMPLETADA'&&['PENDIENTE','OBSERVADA'].includes(p.row.estado_siat)" clickable v-close-popup @click="openReissue(p.row)"><q-item-section avatar><q-icon name="restart_alt" color="orange"/></q-item-section><q-item-section>Reemitir factura</q-item-section></q-item><q-separator/><q-item v-if="can('Anular Ventas')&&p.row.estado==='COMPLETADA'" clickable v-close-popup class="text-negative" @click="cancel(p.row)"><q-item-section avatar><q-icon name="cancel"/></q-item-section><q-item-section>Anular</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template>
      </q-table>
    </q-card>

    <q-dialog v-model="dialog"><q-card style="width:900px;max-width:96vw"><q-card-section class="row items-center q-py-sm"><div><div class="text-subtitle1 text-weight-bold">{{selected.numero}}</div><div class="text-caption">{{formatDate(selected.fecha)}} · {{selected.usuario_nombre}}</div></div><q-space/><q-btn v-if="selected.factura_url" flat dense no-caps icon="open_in_new" color="indigo" label="Impuestos" :href="selected.factura_url" target="_blank"/><q-btn v-if="selected.cuf" flat dense no-caps icon="receipt" color="teal" label="Factura" @click="printSale(selected,'factura')"/><q-btn flat round dense icon="print" color="primary" @click="printSale(selected,'comprobante')"><q-tooltip>Imprimir comprobante</q-tooltip></q-btn><q-badge :color="selected.estado==='COMPLETADA'?'positive':'negative'" :label="selected.estado"/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-table dense flat :rows="selected.detalles||[]" :columns="detailColumns" row-key="id" hide-pagination :rows-per-page-options="[0]"><template #body-cell-precio_cambiado="p"><q-td :props="p"><q-chip dense square :color="p.row.precio_cambiado?'negative':'positive'" text-color="white" :icon="p.row.precio_cambiado?'price_change':'check_circle'">{{p.row.precio_cambiado?'PRECIO CAMBIADO':'SIN CAMBIO'}}</q-chip></q-td></template><template #body-cell-total="p"><q-td :props="p">Bs {{money(p.value)}}</q-td></template></q-table><q-separator/><q-card-section class="q-pa-sm"><div class="row"><span>Subtotal</span><q-space/>Bs {{money(selected.subtotal)}}</div><div class="row text-negative"><span>Descuento</span><q-space/>- Bs {{money(selected.descuento)}}</div><div class="row"><span>Efectivo</span><q-space/>Bs {{money(selected.monto_efectivo)}}</div><div class="row"><span>QR</span><q-space/>Bs {{money(selected.monto_qr)}}</div><div class="row text-h6 text-primary"><b>Total</b><q-space/><b>Bs {{money(selected.total)}}</b></div></q-card-section></q-card></q-dialog>
    <q-dialog v-model="reissueDialog"><q-card style="width:420px;max-width:96vw"><q-card-section class="q-pb-none"><div class="text-subtitle1 text-weight-bold">Reemitir factura N° {{reissueRow.numero_factura}}</div><div class="text-caption text-negative">{{reissueRow.siat_mensaje}}</div></q-card-section><q-card-section><ClienteFactura v-model:cliente="reissueClient"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn unelevated no-caps color="primary" icon="send" label="Reemitir" :loading="reissuing" @click="reissue"/></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="cancelDialog"><q-card style="width:420px;max-width:96vw"><q-card-section><div class="text-subtitle1 text-weight-bold">Anular {{cancelRow.numero}}</div><div class="text-caption">La factura N° {{cancelRow.numero_factura}} se anulará en Impuestos y el stock será restaurado.</div></q-card-section><q-card-section class="q-pt-none"><q-select v-model="cancelReason" :options="cancelReasons" option-label="descripcion" option-value="codigo" emit-value map-options dense outlined label="Motivo de anulación"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn unelevated no-caps color="negative" icon="cancel" label="Anular" :disable="!cancelReason" :loading="cancelling" @click="doCancel"/></q-card-actions></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import {computed,getCurrentInstance,reactive,ref} from 'vue'
import {printSale} from '../../addons/ventaPrint'
import ClienteFactura from '../../components/ClienteFactura.vue'
import {clienteVacio} from '../../stores/carritos-store'
// Fecha local (no UTC): con toISOString, después de las 20:00 en Bolivia el "hoy" saltaría al día siguiente.
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
const {proxy}=getCurrentInstance(),rows=ref([]),loading=ref(false),search=ref(''),from=ref(today()),to=ref(today()),fromTime=ref('00:01'),toTime=ref('23:59'),user=ref(null),receiptType=ref(null),siatState=ref(null),dialog=ref(false),exporting=ref(null),selected=reactive({}),summary=reactive({efectivo:0,qr:0,total:0,descuento:0,cantidad:0,facturas:0,facturas_pendientes:0,usuarios:[]})
const pagination=ref({page:1,rowsPerPage:15,rowsNumber:0}),money=v=>Number(v||0).toFixed(2),can=p=>proxy.$store.hasPermission(p)
// Cantidad sin ceros de relleno: 2 para piezas, 0.355 para peso.
const qty=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):String(parseFloat(n.toFixed(3)))}
function resetToday(){from.value=today();to.value=today();fromTime.value='00:01';toTime.value='23:59';search.value='';user.value=null;receiptType.value=null;siatState.value=null;load(true)}
const cards=computed(()=>[{label:'Total vendido',value:summary.total,money:true,icon:'trending_up',color:'primary'},{label:'Efectivo',value:summary.efectivo,money:true,icon:'payments',color:'green'},{label:'QR',value:summary.qr,money:true,icon:'qr_code_2',color:'blue'},{label:'Ventas',value:summary.cantidad,money:false,icon:'receipt_long',color:'purple'},{label:'Facturas',value:summary.facturas,money:false,icon:'receipt',color:'teal'},{label:'Facturas por resolver',value:summary.facturas_pendientes,money:false,icon:'report',color:'orange'}])
const columns=[{name:'actions',label:'',align:'left'},{name:'numero',label:'Nº venta',field:'numero',align:'left'},{name:'fecha',label:'Fecha',field:r=>formatDate(r.fecha),align:'left'},{name:'usuario',label:'Usuario',field:'usuario_nombre',align:'left'},{name:'comprobante',label:'Comprobante',field:'numero_factura',align:'left'},{name:'tipo_pago',label:'Pago',field:'tipo_pago',align:'center'},{name:'detalles',label:'Productos',field:'detalles_count',align:'left'},{name:'descuento',label:'Descuento',field:'descuento',format:v=>`Bs ${money(v)}`,align:'right'},{name:'total',label:'Total',field:'total',align:'right'},{name:'estado',label:'Estado',field:'estado',align:'center'},{name:'estado_siat',label:'Impuestos',field:'estado_siat',align:'center'}]
const detailColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Producto',field:'nombre',align:'left'},{name:'cantidad',label:'Cant.',field:'cantidad',align:'center'},{name:'precio_base',label:'Precio base',field:'precio_base',format:v=>`Bs ${money(v)}`,align:'right'},{name:'precio',label:'Precio aplicado',field:'precio_venta',format:v=>`Bs ${money(v)}`,align:'right'},{name:'precio_cambiado',label:'Cambio',field:'precio_cambiado',align:'center'},{name:'total',label:'Total',field:'total',align:'right'}]
const params=()=>({q:search.value,desde:from.value,hasta:to.value,hora_desde:fromTime.value,hora_hasta:toTime.value,user_id:user.value?.id,tipo_comprobante:receiptType.value,estado_siat:siatState.value}),paymentColor=v=>v==='EFECTIVO'?'green':v==='QR'?'blue':'purple'
function formatDate(v){return v?new Date(v).toLocaleString('es-BO'):''}
function load(resetPage=false){onRequest({pagination:resetPage?{...pagination.value,page:1}:pagination.value})}
function loadSummary(){proxy.$axios.get('/ventas-resumen',{params:params()}).then(r=>Object.assign(summary,r.data))}
function onRequest({pagination:p}){loading.value=true;proxy.$axios.get('/ventas',{params:{...params(),page:p.page,per_page:p.rowsPerPage}}).then(r=>{rows.value=r.data.data;pagination.value={...p,rowsNumber:r.data.total};loadSummary()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudieron cargar las ventas')).finally(()=>loading.value=false)}
function showDetail(row){proxy.$axios.get(`/ventas/${row.id}`).then(r=>{Object.assign(selected,r.data);dialog.value=true})}function printRow(row,formato='auto'){proxy.$axios.get(`/ventas/${row.id}`).then(r=>printSale(r.data,formato)).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo imprimir'))}
// Una factura validada se anula primero en Impuestos, con el motivo que exige el SIN.
const cancelDialog=ref(false),cancelRow=ref({}),cancelReason=ref(null),cancelReasons=ref([]),cancelling=ref(false)
function cancel(row){if(row.tipo_comprobante==='FACTURA'&&row.estado_siat==='VALIDADA'){cancelRow.value=row;cancelReason.value=null;cancelDialog.value=true;if(!cancelReasons.value.length)proxy.$axios.get('/ventas-motivos-anulacion').then(r=>cancelReasons.value=r.data);return}proxy.$alert.dialog(`¿Anular la venta ${row.numero}? El stock será restaurado.`).onOk(()=>proxy.$axios.put(`/ventas/${row.id}/anular`).then(()=>{proxy.$alert.success('Venta anulada');load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo anular')))}
function doCancel(){cancelling.value=true;proxy.$axios.put(`/ventas/${cancelRow.value.id}/anular`,{codigo_motivo:cancelReason.value}).then(()=>{proxy.$alert.success('Factura anulada en Impuestos','La venta fue anulada y el stock restaurado');cancelDialog.value=false;load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo anular')).finally(()=>cancelling.value=false)}
const siatStates=[{label:'Validada',value:'VALIDADA'},{label:'Por enviar (evento)',value:'PENDIENTE_EVENTO'},{label:'Observada',value:'OBSERVADA'},{label:'Pendiente',value:'PENDIENTE'},{label:'Anulada',value:'ANULADA'}]
const siatLabel=v=>siatStates.find(s=>s.value===v)?.label||v,siatColor=v=>({VALIDADA:'positive',PENDIENTE_EVENTO:'orange',OBSERVADA:'negative',PENDIENTE:'grey-7',ANULADA:'blue-grey'}[v]||'grey')
// El PDF se genera en el servidor en ese momento; no queda guardado allá.
function downloadPdf(row){proxy.$axios.get(`/ventas/${row.id}/factura-pdf`,{responseType:'blob'}).then(r=>{const url=URL.createObjectURL(r.data),a=document.createElement('a');a.href=url;a.download=`Factura_${row.numero_factura}.pdf`;a.click();URL.revokeObjectURL(url)}).catch(()=>proxy.$alert.error('No se pudo generar el PDF'))}
function sendMail(row){proxy.$alert.dialogPrompt(row.cliente_email?`Factura N° ${row.numero_factura}: deje vacío para enviarla a ${row.cliente_email} o escriba otro correo`:`Correo del cliente para la factura N° ${row.numero_factura}`).onOk(email=>proxy.$axios.post(`/ventas/${row.id}/enviar-factura`,{email:String(email||'').trim()||null}).then(r=>{proxy.$alert.success(r.data.mensaje,'Se adjuntó el PDF y el XML');load()}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo enviar el correo')))}
function verify(row){proxy.$axios.get(`/ventas/${row.id}/verificar-factura`).then(r=>{proxy.$alert.info(`Impuestos: ${r.data.mensaje||r.data.estado_siat}`,`Factura N° ${row.numero_factura} · estado ${siatLabel(r.data.estado_siat)}`);load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo consultar a Impuestos'))}
// Reemisión de una factura que Impuestos rechazó o que no llegó a emitirse; se pueden corregir los datos del cliente.
const reissueDialog=ref(false),reissueRow=ref({}),reissueClient=ref(clienteVacio()),reissuing=ref(false)
function openReissue(row){reissueRow.value=row;reissueClient.value={...clienteVacio(),tipo_documento:row.tipo_documento||'CI',numero_documento:row.numero_documento==='99002'?'':row.numero_documento||'',complemento:row.complemento||'',cliente_nombre:row.numero_documento==='99002'?'':row.cliente_nombre||'',cliente_email:row.cliente_email||''};reissueDialog.value=true}
function reissue(){reissuing.value=true;proxy.$axios.put(`/ventas/${reissueRow.value.id}/reemitir-factura`,reissueClient.value).then(r=>{const d=r.data;if(d.estado_siat==='VALIDADA')proxy.$alert.success(`Factura N° ${d.numero_factura} validada por Impuestos`);else if(d.estado_siat==='PENDIENTE_EVENTO')proxy.$alert.warning('Factura emitida sin conexión','Se enviará con un evento significativo');else proxy.$alert.error('Impuestos volvió a rechazarla',d.siat_mensaje||'');reissueDialog.value=false;load();if(d.cuf)printSale(d)}).catch(e=>proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo reemitir')).finally(()=>reissuing.value=false)}
// El nombre lleva el rango consultado para que no se pisen los archivos en la carpeta de descargas.
function exportName(type){const ext=type==='excel'?'xlsx':'pdf',rango=from.value===to.value?from.value:`${from.value}_a_${to.value}`;return `ventas_${rango||'todas'}.${ext}`}
async function download(type){if(exporting.value)return;exporting.value=type
  try{const response=await proxy.$axios.get(`/ventas-exportar/${type}`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download=exportName(type);a.click();URL.revokeObjectURL(url);proxy.$alert.success('Reporte generado',type==='excel'?'Incluye la hoja Precios modificados':'Descarga lista')}
  catch{proxy.$alert.error('No se pudo exportar el reporte')}
  finally{exporting.value=null}}
async function downloadChangedPrices(type){if(exporting.value)return;exporting.value=`changed-${type}`
  try{const response=await proxy.$axios.get(`/ventas-exportar/precios-modificados/${type}`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a'),ext=type==='excel'?'xlsx':'pdf',rango=from.value===to.value?from.value:`${from.value}_a_${to.value}`;a.href=url;a.download=`precios_modificados_${rango||'todos'}.${ext}`;a.click();URL.revokeObjectURL(url);proxy.$alert.success('Reporte de precios modificados generado')}
  catch{proxy.$alert.error('No se pudo exportar el reporte de precios modificados')}
  finally{exporting.value=null}}
load()
</script>

<style scoped>.summary-card{border-radius:10px}
.items-list{max-width:280px;padding:1px 0}
.items-row{font-size:9px;line-height:1.35;color:#5f5f5f;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
</style>
